export const SKIP_DIRS = new Set([
  ".git", "node_modules", "__pycache__", ".venv", "venv",
  ".next", "dist", "build", ".cache", ".pi", ".pi-coding-agent",
  ".svelte-kit", ".output", ".nuxt",
]);

export const DEFAULT_MODEL = "anthropic/claude-sonnet-4-5-20250929";

export const DOC_PATTERNS = new Set([
  "README.md", "README.txt", "README.rst",
  "CONTRIBUTING.md", "CHANGELOG.md",
  "ARCHITECTURE.md", "DESIGN.md", "STYLE.md",
]);

export const LANG_MAP: Record<string, string> = {
  ".ts": "typescript", ".tsx": "typescript", ".js": "javascript",
  ".jsx": "javascript", ".py": "python", ".rs": "rust",
  ".go": "go", ".java": "java", ".rb": "ruby",
  ".php": "php", ".cs": "csharp", ".cpp": "cpp", ".c": "c",
  ".swift": "swift", ".kt": "kotlin", ".ex": "elixir", ".exs": "elixir",
  ".lua": "lua", ".scala": "scala", ".md": "markdown",
  ".json": "json", ".yaml": "yaml", ".yml": "yaml",
  ".toml": "toml", ".xml": "xml", ".html": "html",
  ".css": "css", ".scss": "scss", ".less": "less",
  ".sh": "shell", ".bash": "shell", ".zsh": "shell",
};

export const TOOL_SIGNATURES: Record<string, { type: string; value: string }> = {
  // Lockfiles first — more specific than package.json
  "yarn.lock": { type: "packageManager", value: "yarn" },
  "package-lock.json": { type: "packageManager", value: "npm" },
  "pnpm-lock.yaml": { type: "packageManager", value: "pnpm" },
  "uv.lock": { type: "packageManager", value: "uv" },
  "poetry.lock": { type: "packageManager", value: "poetry" },
  // Then generic manifests
  "package.json": { type: "packageManager", value: "npm/yarn" },
  "Cargo.toml": { type: "packageManager", value: "cargo" },
  "go.mod": { type: "packageManager", value: "go modules" },
  "requirements.txt": { type: "packageManager", value: "pip" },
  "pyproject.toml": { type: "packageManager", value: "pip/setuptools" },
  "Pipfile": { type: "packageManager", value: "pipenv" },
  "Gemfile": { type: "packageManager", value: "bundler" },
  "vitest.config.ts": { type: "testFramework", value: "vitest" },
  "vitest.config.js": { type: "testFramework", value: "vitest" },
  "vitest.config.mts": { type: "testFramework", value: "vitest" },
  "jest.config.js": { type: "testFramework", value: "jest" },
  "jest.config.ts": { type: "testFramework", value: "jest" },
  "vitest.config.cts": { type: "testFramework", value: "vitest" },
  "conftest.py": { type: "testFramework", value: "pytest" },
  "pytest.ini": { type: "testFramework", value: "pytest" },
  ".mocharc.yml": { type: "testFramework", value: "mocha" },
  ".mocharc.json": { type: "testFramework", value: "mocha" },
  "eslint.config.js": { type: "linter", value: "eslint (flat)" },
  "eslint.config.mjs": { type: "linter", value: "eslint (flat)" },
  ".eslintrc": { type: "linter", value: "eslint" },
  ".eslintrc.js": { type: "linter", value: "eslint" },
  ".eslintrc.json": { type: "linter", value: "eslint" },
  "ruff.toml": { type: "linter", value: "ruff" },
  ".flake8": { type: "linter", value: "flake8" },
  ".golangci.yml": { type: "linter", value: "golangci-lint" },
  ".golangci.yaml": { type: "linter", value: "golangci-lint" },
  ".rubocop.yml": { type: "linter", value: "rubocop" },
  ".prettierrc": { type: "formatter", value: "prettier" },
  ".prettierrc.json": { type: "formatter", value: "prettier" },
  ".prettierrc.js": { type: "formatter", value: "prettier" },
  "prettier.config.js": { type: "formatter", value: "prettier" },
  "biome.json": { type: "formatter", value: "biome" },
  "biome.jsonc": { type: "formatter", value: "biome" },
  ".gitlab-ci.yml": { type: "ciSystem", value: "gitlab ci" },
  "Jenkinsfile": { type: "ciSystem", value: "jenkins" },
  "travis.yml": { type: "ciSystem", value: "travis ci" },
  ".travis.yml": { type: "ciSystem", value: "travis ci" },
  "tsconfig.json": { type: "buildTool", value: "typescript" },
  "vite.config.ts": { type: "buildTool", value: "vite" },
  "vite.config.js": { type: "buildTool", value: "vite" },
  "next.config.js": { type: "buildTool", value: "next.js" },
  "next.config.mjs": { type: "buildTool", value: "next.js" },
  "tailwind.config.js": { type: "buildTool", value: "tailwind" },
  "tailwind.config.ts": { type: "buildTool", value: "tailwind" },
  "Makefile": { type: "buildTool", value: "make" },
  "Dockerfile": { type: "buildTool", value: "docker" },
  "docker-compose.yml": { type: "buildTool", value: "docker compose" },
  "docker-compose.yaml": { type: "buildTool", value: "docker compose" },
  "AGENTS.md": { type: "agentDoc", value: "AGENTS.md" },
  "CLAUDE.md": { type: "agentDoc", value: "CLAUDE.md" },
  "GEMINI.md": { type: "agentDoc", value: "GEMINI.md" },
};
